name: lc0-cpu # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.26.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Leela Chess Zero chess engine # 79 char long summary
description: |
  This is a test build of the Leela Chess Zero chess engine.
  https://github.com/LeelaChessZero/lc0/

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  lc0:
    command: bin/lc0

parts:
  meson-project:
    plugin: meson
    meson-parameters:
    - -Dbuildtype=release
    - -Dgtest=False
    build-packages:
    - gcc-8
    - g++-8
    - libstdc++-8-dev
    - libopenblas-dev
    - libeigen3-dev
    build-environment:
    - CC: "gcc-8"
    - CXX: "g++-8"
    stage-packages:
    - libopenblas-dev
    - libeigen3-dev
    override-build: |
      pip3 install --upgrade meson==0.55.3
      snapcraftctl build
    source: https://github.com/LeelaChessZero/lc0.git
    source-depth: 1
    source-tag: 'v0.26.3'
